name: Heroku github actions CI and CD demo

on:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Build and analyse with Sonar
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          SONAR_TOKEN: ${{secrets.SONAR_CLOUD_TOKEN}}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=picomSpringBoot
      - name: Deploy on Heroku
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with: #below are the secrete
          heroku_api_key: ${{secrets.SBHEROKU_API_KEY}}
          heroku_email: ${{secrets.SBHEROKU_EMAIL}}
          heroku_app_name: ${{secrets.SBHEROKU_APP}}